language: swift
osx_image: xcode10.2
cache:
  bundler: true
  cocoapods: true
  slather: true
addons:
  homebrew:
    packages:
      - swiftlint
before_install:
  - rvm use $RVM_RUBY_VERSION
install:
  - gem install cocoapods --pre
  - pod install --repo-update
  - gem install slather
script:
  # - make build
  - xcodebuild \
	-workspace strolling-of-time-ios.xcworkspace \
	-configuration Debug \
	-scheme strolling-of-time-ios \
	-destination 'platform=iOS Simulator,OS=${OS_VERSION},name=iPhone 7' \
	-enableCodeCoverage YES \
	test \
	CODE_SIGN_IDENTITY="" \
	CODE_SIGNING_REQUIRED=NO \
	ONLY_ACTIVE_ARCH=NO \
  -quiet
  - slather
after_success:
  - bash <(curl -s https://codecov.io/bash) -f ./report/cobertura.xml -X coveragepy -X gcov -X xcode
  - echo $PWD && ls -al report
