language: swift
osx_image: xcode10.2
cache:
  bundler: true
  cocoapods: true
addons:
  homebrew:
    packages:
      - swiftlint
before_install:
  - gem install cocoapods --pre
  - gem install slather
  - pod install --repo-update
script:
  - make lint build
after_success:
  - slather
  - bash <(curl -s https://codecov.io/bash) \
    -f report/cobertura.xml \
    -X coveragepy \
    -X gcov \
    -X xcode
