language: swift
osx_image: xcode10
before_install:
  - gem install cocoapods --pre
install:
  - ./install_swiftlint.sh
script:
  - pod install --repo-update
  - swiftlint
  - xcodebuild -workspace strolling-of-time-ios.xcworkspace -scheme strolling-of-time-ios -derivedDataPath BuildFolder/ -destination 'platform=iOS Simulator,OS=12.0,name=iPhone 7' -enableCodeCoverage YES clean build test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet
