language: swift
osx_image: xcode10.2
cache:
  bundler: true
  cocoapods: true
  slather: true
addons:
  homebrew:
    packages:
      - swiftlint
before_install:
  - rvm use $RVM_RUBY_VERSION
install:
  - gem install cocoapods --pre
  - pod install --repo-update
  - gem install slather -v '~>2.4.7'
script:
  - make build
after_success:
  - slather coverage --coveralls
  - echo $PWD && ls -al report
