language: swift
os: osx
osx_image: xcode10.2
cache:
  bundler: true
  cocoapods: true
  slather: true
addons:
  homebrew:
    packages:
      - swiftlint
before_install:
  - rvm use $RVM_RUBY_VERSION
install:
  - gem install slather --no-document --quiet
  - gem install cocoapods -v '1.6.1'
  - gem install coveralls
  - gem install cocoapods-clean
  - pod repo update
before_script:
  - pod deintegrate
  - pod clean
  - pod setup
  - pod install
script:
  - make build
after_success:
  - slather coverage --coveralls
  - echo $PWD && ls -al report
