language: swift
osx_image: xcode10.2
cache:
  bundler: true
  cocoapods: true
  slather: true
addons:
  homebrew:
    packages:
      - swiftlint
before_install:
  - gem install cocoapods --pre
  - gem install slather
  - pod install --repo-update
script:
  - make build
after_success:
  - echo $PWD && ls -al
  - slather
  - bash <(curl -s https://codecov.io/bash) -f ./report/cobertura.xml -X coveragepy -X gcov -X xcode
