language: swift
osx_image: xcode10.2
cache:
  bundler: true
  cocoapods: true
addons:
  homebrew:
    packages:
      - swiftlint
before_install:
  - gem install cocoapods --pre
  - pod install --repo-update
script:
  - make lint build
after_success:
  - bash <(curl -s https://codecov.io/bash)
